43 fix analytic sum operation returns number when only integers participate
Meaningful-Data/vtlengine pull request #50
Opened 2024-11-22 14:38 UTC by mla2001

2024-11-29 09:41 UTC, javihern98 requested changes
Review changes on class attributes

2024-11-29 09:41 UTC, javihern98 commented on src/vtlengine/Operators/Analytic.py
> +                cls.type_to_check = Number if is_Number else Integer
We cannot change the class attribute, we must use another variable at instance level, or at least add an else clause to ensure we keep it at None or Number

2024-11-29 09:41 UTC, javihern98 commented on src/vtlengine/Operators/Analytic.py
> +                cls.return_type = cls.type_to_check
Same as above

2025-01-14 11:27 UTC, javihern98 commented on src/vtlengine/Operators/Analytic.py
> +                cls.type_to_check = Number if is_Number else Integer
@mla2001 Please check this

2025-01-14 11:27 UTC, javihern98 commented on src/vtlengine/Operators/Analytic.py
> +                cls.return_type = cls.type_to_check
@mla2001 Please check this

2025-01-16 16:55 UTC, mla2001 commented on src/vtlengine/Operators/Analytic.py
> +                cls.return_type = cls.type_to_check
Fixed. Added the intermediary attribute: 
`return_int: bool = False`

2025-01-16 18:13 UTC, javihern98 approved these changes
All good, thanks😁

2025-01-16 18:14 UTC, javihern98 commented
I will merge this ASAP once conflicts are solved

2025-01-16 18:39 UTC, merged